name: Deploy Website

on:
  push:
    branches:
      - main

jobs:
  build-deploy:
    runs-on: self hosted
             macos

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        pip install -r src/requirements.txt || echo "No requirements.txt"

    - name: Build project
      run: |
        python src/main.py

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v4
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./content
